M48
; DRILL file {KiCad 8.0.3} date 2024-08-19T15:25:54-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-19T15:25:54-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X4.8961Y-4.3876
X5.0099Y-4.5847
T2
X5.4771Y-3.3722
X5.6303Y-3.2376
X5.6703Y-3.3069
M30
